### ISSUE TITLE
Search section css amendment

### ISSUE THREAD

**Issue by cagatayldzz** [getkirby/panel#1010]
![ar2-collage](https://cloud.githubusercontent.com/assets/7725575/23202943/1926c0b2-f8e9-11e6-9470-6148815815ce.jpg)

```css
.search-section .icon, 
.search-section a span{
    display: inline-block;
    vertical-align: middle;
    width: 90%;
}
```
chrome: v56.0.2924.87
panel: v2.4.1
