### ISSUE TITLE
using a relative url for dynamic options via JSON API

### ISSUE THREAD

**Issue by bnomei** [getkirby/panel#1035]
using a relative url for select/checkboxes/radio fields like this does not work. 
`options: myroute/select.json`

hardcoding the url of the current server is not ideal when trying to create a plugin. 
creating copy of the field just for that change is not either.

perhaps one could add a dedicated url option and apply the `url()` helper?
that change would not break current implementation.

```yaml
options: url
  url: myroute/select.json
```

```php
else if($this->isUrl($this->field->options)) {
      $this->options = $this->optionsFromApi($this->field->options);
}
else if($this->field->options == 'url') {
      $url = url($this->field->options->url)); // not sure if this works but you get the idea
      $this->options = $this->optionsFromApi($url);
}
```

somewhere around here...
https://github.com/getkirby/panel/blob/bc95bd9e2e640f184439f63610e7955d36fc33f9/app/src/panel/form/fieldoptions.php#L26

**Comment by lukasbestle** [comment]
This is now implemented on the develop branch:

```
fields:
  category:
    label: Category
    type: select 
    default: architecture
    options: url
    url: myroute/select.json
```
