### ISSUE TITLE
override on datetime panel field

### ISSUE THREAD

**Issue by demlak** [getkirby/panel#1051]
Hi, just a feature suggestion:

I would like to use override-feature on datetime panel field.
Currently it seems to be usable only on date-field and time-field as seperated fields.. I would like to use it in the "combined" datetime-field.

Since i'm not a coder, i can't code it myself =(

thx in advance
demlak

**Comment by lukasbestle** [comment]
It's true that this feature is currently not implemented. I have added this as an idea for the next larger release.

**Comment by demlak** [comment]
thx a lot...

is there something like a timeline? or do releases come "from time to time"?

**Comment by lukasbestle** [comment]
It won't be in the next few weeks for sure.
But if we decide to build this feature, it will be possible for you to temporarily make the changes in your current Kirby installation without having to wait for the release. I will let you know.

**Comment by lukasbestle** [comment]
I actually fixed this for the next release already as I was updating the `datetime` field anyway.

You can try it out by using the `develop` branch of the Panel. Or it will be in v2.5.0, which will be out soon.

Syntax for this feature:

```yaml
fields:
  date:
    label: Date & time
    type: datetime
    date:
      override: true
    time:
      override: true
```

**Comment by lukasbestle** [comment]
Correction: The syntax looks like this:

```yaml
fields:
  date:
    label: Date & time
    type: datetime
    override: true
    readonly: true
```

**Comment by demlak** [comment]
wow.. thx a lot!

seems to work.. but setting interval is ignored? or default 60 min.? i did not test if it is 60 min.. have to wait till next hour for it *g*

**Comment by lukasbestle** [comment]
No, you can set the interval like this:

```
fields:
  date:
    label: Date & time
    type: datetime
    required: true
    time:
      interval: 15
```

**Comment by demlak** [comment]
ok.. finaly.. this seems to work for me... (date test will follow on another day \*g\*

``` yaml
  lastupdate:
    label:  lastupdate
    type:   datetime
    width:  1/2
    override: true
    time:
      interval: 1
      default: now
      override: true
    date:
      default: now
      override: true
```

thx a lot!

**Comment by lukasbestle** [comment]
Actually the same result can be achieved even simpler (and you should do it like this to ensure compatibility):

```yaml
  lastupdate:
    label:    lastupdate
    type:     datetime
    width:    1/2
    default:  now
    override: true
    readonly: true
    time:
      interval: 1
```
