### ISSUE TITLE
Toggle field error

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#1063]
Kirby 2.5

```yml
fields:
  toggletext:
    type: toggle
```

>Error
Method ToggleField::__toString() must not throw an exception, caught Error: Call to a member function tag() on null

The weird thing is that when adding a label it works.
