### ISSUE TITLE
Site sidebar missing style

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#1070]
![image](https://user-images.githubusercontent.com/927011/27794628-341da1fc-6003-11e7-8ffd-ab54de94f15b.png)

Below the site files there are no margin bottom in site options. On the page sidebar there are. So a style is missing. I added a fix for it here.

https://github.com/jenstornell/kirby-headline-jump/blob/master/fields/headlinejump/assets/css/style.css#L51

Because site has no data after files it can be debatable if it's really a bug or not. Only when plugins add data to it, it's a problem. To be future proof, I think there should be a margin bottom. Another reason is that both the sidebars should work the same way.

```css
.sidebar-content > .section > .marginalia {
    margin-bottom: 1.5em;
    line-height: 1.5em;
}
```

The above is a quickfix, but fixing the [sidebar inconsistancy](https://github.com/getkirby/panel/issues/1069) should fix this as well and that would be the better solution.
