### ISSUE TITLE
Password panel field stores value in plain text

### ISSUE THREAD

**Issue by samnabi** [getkirby/panel#1098]
I'm implementing a "private page" feature so site admins can share pages with only trusted people – these people will not have user accounts though.

I have a password field in a page blueprint, like this:

```
  password:
    label: Page password
    type: password
    help: Required if page is marked private
```

When the page is saved, the password value is recorded in plaintext in the content file.

Shouldn't it be hashed, or am I missing something?
