### ISSUE TITLE
Disabled and/or Readonly Checkbox Field Easily Bypassed

### ISSUE THREAD

**Issue by neildaniels** [getkirby/panel#1118]
When a blueprint file specifies a `checkbox` field, its value can be easily changed in the panel, even if `disabled` and/or `readonly` is set.

```
    isDraft:
        label: Draft
        type: checkbox
        text: Draft
        width: 1/5
        disabled: true
        readonly: true
```

## Disabled
In the case of `disabled`, absolutely no protection is provided in the Panel. The only difference is a lowered opacity. The checkbox, label, and header are all easily clickable and will change the state of the checkbox value.

![disabled checkbox](https://user-images.githubusercontent.com/417182/32679175-46d728e0-c61a-11e7-93dd-236c1ce836a0.gif)

## Readonly
In the case of `readonly`, the checkbox and accompanying label (what the Blueprint called "text") are correctly disabled. However, the header (what the Blueprint calls "label") is still clickable and will change the state of the checkbox value.

![readonly checkbox](https://user-images.githubusercontent.com/417182/32679178-4bbc1d16-c61a-11e7-9249-3fc0e5a15562.gif)

If both `disabled` and `readonly` are specified, then the behavior is identical to `readonly`, but the visual styling is that of `disabled`.

In all cases, I would expect that the checkbox should not be modifiable at all.
