### ISSUE TITLE
Radio-button switches back to previous value on save

### ISSUE THREAD

**Issue by DerZyklop** [getkirby/panel#112]
I have a radio-btn in my blueprint. I [figured out the new syntax for radio-buttons](https://github.com/getkirby/panel/issues/51#issuecomment-51781171). So my blueprint-entry now looks like this: 

```
  language:
    label: Language
    type: radio
    options:
      deutsch: Deutsch
      english: English
    default: deutsch
```

But i have an article where the radio-button doesn’t work:

![language](https://cloud.githubusercontent.com/assets/912344/3878855/0c7ff8f6-2173-11e4-9023-96826fe68dd0.gif)
