### ISSUE TITLE
Simple way to combine dynamic options in select field?

### ISSUE THREAD

**Issue by maximelebreton** [getkirby/panel#1152]
Hi all!

Is there a way to combine dynamic options in the select field?
https://getkirby.com/docs/cheatsheet/panel-fields/select

I would like to combine `pages` and `files` options:

Option | Description
-- | --
pages | List of options with all **pages of the site**
files | List of options with all **files of the page**

```yaml
fields:
  url:
    label: Link to page or file
    type: select 
    options: pages, files # <-- combine all pages of the site, with all files of the page
```

Thanks!
