### ISSUE TITLE
headline inside structure field

### ISSUE THREAD

**Issue by DerZyklop** [getkirby/panel#136]
I assumed that all fields are working inside a `structure` field. But a headline like this: 

```
adressen:
  label: Adressen
  type: structure
  fields:
    headline:
      label: Adresse
```

gives me that: 

```
Catchable fatal error: Method Field::__toString() must return a string value 
in /Users/derzyklop/Cloud/server/pxwrk.de/jota.pxwrk.de/kirby/toolkit/lib/brick.php on line 165
```
