### ISSUE TITLE
Field content not being saved when field name contains a dash

### ISSUE THREAD

**Issue by ian-cox** [getkirby/panel#139]
I've noticed that field content doesn't save when the field name (specified in the blueprint) contains a dash. CamelCase doesn't seem to work either.

```
fields:
  title:
    label: Title
    type:  text
  project-intro:
    label: Projects Intro Text
    type:  textarea
```
