### ISSUE TITLE
Not possible to edit caption

### ISSUE THREAD

**Issue by bugsysop** [getkirby/panel#155]
I added this to my _blueprints/project.php_ file:

```
filefields: 
  caption: 
    label: Caption
    type:  text
```

But it's not possible do edit the captions with te panel, even if I create “manually” the file...
