### ISSUE TITLE
Date validation in file fields

### ISSUE THREAD

**Issue by skifreak** [getkirby/panel#160]
I have the following setup in a blueprint:

```
title: Photo
pages: true
files: true
  fields:
    artist:
      label: Arist Name
      type:  text
    postdate:
      label: Posting Date
      type: date
      format: MM/DD/YYYY
    caption: 
      label: Caption
      type:  text
```

Inputting a date doesn't pass the validation:

![recording](http://cl.ly/image/1D123C3G3Y1g/Screen%20Recording%202014-08-31%20at%2003.55%20PM.gif)

The result is the same without a custom format. The validation works as expected in the main page fields.
