### ISSUE TITLE
Fetching date data from structure field

### ISSUE THREAD

**Issue by petephm** [getkirby/panel#171]
Hey Bastian,

I'm working with a structure field and I am trying to fetch the date data in each entry with a foreach loop.

```
testimonial_post:
    label: Testimonial Entries
    type: structure
    fields:
      quote:
        label: Quote
        type: textarea
        icon: align-left
        required: true
        icon: quote-right
      date:
        label: Date
        type: date
        required: true
      occasion:
        label: Occasion
        type: text
        icon: question
      client:
        label: Client Name
        type: text
        required: true
        icon: user
      text:
        label: Full Testimonial
        type: textarea
        icon: align-left
```

When I fetch the date with **$structure['date']** it returns the whole date as **'YYYY-mm-dd'**

But when I try to format the date data from within the structure field with: 

```
<?php echo $structure['date']->date('d F') ?> 
```

OR

```
<?php 
$d = $structure['date'];
echo date('d F', $d);
?>
```

This breaks my entire page layout. It’d be cool to be able to fetch only certain parameters of the date in structured fields as well.
