### ISSUE TITLE
Hide Error and Home page

### ISSUE THREAD

**Issue by ghost** [getkirby/panel#186]
Would be nice to be able to hide the Error & Home page in the Dashboard for clients.

**Comment by mzur** [comment]
It would be nice to be able to hide *any* page, maybe like this:

```
title: Sitemap
hide: true
fields:
  title:
    label: Titel
    type:  text
```
Which automatically sets `pages`, `files` and `deletable` to `false` as well as all fields to `readonly`.
