### ISSUE TITLE
Default option for toggle

### ISSUE THREAD

**Issue by xu-chris** [getkirby/panel#209]
I've tried to set default options for toggles, but computer says "No". ;-)
Is it possible to set a default value for a toggle field? 

This is my blueprint snippet; I've tried with "yes" and "true" but nothing happens here:

```
  pause:
    label: Ist bei diesem Stück eine Pause eingeplant?
    type: toggle
    text: yes/no
    default: true
    help: >
      Bei angekreuzt wird automatisch eine Pause von 20 Minuten angegeben.
    width: 1/2
```
