### ISSUE TITLE
Kirby panel on mac saves malformed content files

### ISSUE THREAD

**Issue by mcbrwr** [getkirby/panel#283]
Maybe I'm doing something wrong here.. But here's the thing: I'm trying to run a fresh checkout of the starterkit on my mac. Apache: 2.4.9 / PHP 5.5.14, both recently installed with macports. Some other, kirby v1 sites run like a charm, but the current version has a weird issue: Whenever I save a content file (even the supplied default page) the content file seems malformed. The field titles are truncated to the first letter, which is set in capital. The default blueprint is like this:

```
<?php if(!defined('KIRBY')) exit ?>

title: Page
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
  content:
    label: Text
    type:  textarea
```

And when I save a new or existing file the resulting content file looks like this:

```
T: testpage

----

C: lorem ipsum
```

I have cloned the project to a debian server and there's no sign of the issue there. So I assume it has something to do with the local environment. Is this something I'm doing wrong or might this be a (known) bug?
