### ISSUE TITLE
Date-Field with custom format ignores custom format when saving

### ISSUE THREAD

**Issue by webgefrickel** [getkirby/panel#294]
Hi there. First things first: kirby 2 and the new panel are awesome. I love it, customers love it!

I created a blueprint for a simple news-page, like this:

```
fields:
  [...]
  newsdate:
    label:  Datum der News
    type:   date
    format: DD.MM.YYYY
  [...]
```

Everything works fine in the panel and the picked/saved date will be shown as sth. like 24.11.2014
Buy the field stored in the actual text-file still is in the default format of YYYY-MM-DD (2014-11-24 for this example).

Is this the intended behaviour? I think there is nothing wrong with a short

```
<?= date("d.m.Y", strtotime($news->newsdate()) ?>
```

or handling this in a controller. Just wanted to know if that's the way it should be.

Thanks!
