### ISSUE TITLE
Add support for multilingual help texts

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/panel#31]
### Blueprint

```
  text:
    label: Text
    help:
      de:  Weit hinten, hinter den Wortbergen, fern der Länder Vokalien und Konsonantien leben die Blindtexte.
      en:  Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
```
### Display in Panel

```
{
  "de": "Weit hinten, hinter den Wortbergen, fern der Länder Vokalien und Konsonantien leben die Blindtexte.", 
  "en": "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
}
```
