### ISSUE TITLE
Decimals in number field

### ISSUE THREAD

**Issue by skifreak** [getkirby/panel#334]
It looks like the number field currently supports only whole numbers. Support for decimals here would be great.
Or am I just missing something?

**Comment by bastianallgeier** [comment]
I just added a fix for this to the develop branch.
You can now set the step, min and max

```
myfield: 
  label: My number
  type: number
  step: 0.5
  min: 0
  max: 100
```
