### ISSUE TITLE
Select field returns partial URI

### ISSUE THREAD

**Issue by peterph-am** [getkirby/panel#336]
Hi Bastian,

The select field in kirby doesn't return a full URI for a page,

for example if I set the options to pages:

````
something:
  label: Some Links
  type: select
  options: pages
````

And in my field I select a page which is 2 levels down from the root, i.e. "Blog Post 02"

However the URI returned will be "blog-post-02" not a full URI like "/blog/blog-post-02"

*I am using the latest version of Kirby & Kirby Panel through git submodules*

Cheers

**Comment by peterph-am** [comment]
Would be good if this could be implemented. The 'pages' option isn't useful if you can't use the selected option to create a url from the URI

**Comment by DerZyklop** [comment]
+1

Hey @peterph-am .. have you found a solution for this? Is there an easy way to search for pages by name/id?

**Comment by DerZyklop** [comment]
is this really just an enhancement? a page-select that returns non-unique values seems useless to me.

**Comment by bastianallgeier** [comment]
Man, 8 months! I'm so sorry, but I got so deep into the new version that I hardly manage to answer stuff here. There's actually a pretty good alternative for this: 

```
 relatedPages: 
    label: Related Pages
    type: select
    options: query
    query: 
      fetch: siblings
      value: "{{uri}}"
      text: "Page: {{title}}"
```

With this you have full control over the value and also the text of each option.
