### ISSUE TITLE
Sort select field options

### ISSUE THREAD

**Issue by FabianSperrle** [getkirby/panel#399]
Especially for long option lists as generated e.g. by the `pages` option being able to sort the list would be great. Otherwise I don't see what I would need the `flip` parameter for.

**Comment by distantnative** [comment]
But you can do that already:

```
  select:
    labe: Project files
    type: select
    options: query
    query:
      page: projects/project-a
      fetch: files
      value: '{{filename}}'
      text: '{{filename}}'
    sort: desc
```
