### ISSUE TITLE
Sort subpages by field not working

### ISSUE THREAD

**Issue by puleddu** [getkirby/panel#401]
Setting my blueprint for an `events` collection page, like this:

````
title: Events
pages:
  template:
    - event
    - webinar
  sort: flip
  limit: 20
  num: date
  field: datestart
````

Should make the numbering of my `event` pages ordered by `datestart`.
It doesn't work. Only the default `date` field works correctly when numbering by date is enabled.
