### ISSUE TITLE
Query Options for checkboxes/Select fields

### ISSUE THREAD

**Issue by A-Monkey** [getkirby/panel#432]
Hi all,

Having a hard time to get this to work, if it´s now supposed to work ?!
Fetch all pages in page "category" that have the value "cat"(checkbox)  true .

```
category:
        label: Category
        type: checkboxes
        options: query
        query:
            page: category
            fetch: index
            value: '{{cat}}'
            text: '{{title}}'
```

Best regards /

Fred

**Comment by A-Monkey** [comment]
sorry, just realized that this is not going to work, burned some braincells in the process, DOH !!

What would be nice is this : 
```
category:
        label: Category
        type: checkboxes
        options: query
        query:
            page: category
            fetch: index
            query: "if the checkbox field 'category' is true(checked) for the page in 'category' then go ahead and fetch the value and text"
            value: '{{uid}}'
            text: '{{title}}'
```
