### ISSUE TITLE
Structure field validation not working

### ISSUE THREAD

**Issue by mzur** [getkirby/panel#434]
Take a look at this structure field definition in the blueprint:
```
events:
   label: Events
   type: structure
   fields:
      time:
         label: Time
         type: text
         validate: 
            match: >
               [0-9]{2}\:[0-9]{2}
```
So the `time` field is validated to contain a time formatted like `HH:MM` (let's forget about the `time` field type for now) .

This validation is completey ignored by the popup for editing the field item. I'm able to enter random values, hit "Save" to close the popup and "Save" the new page contents. The popup *does* display the `time` field in an error state when I reopen it again but that doesn't affect my ability to save at all.

Am I doing something wrong or is the validation really bypassed in this case?
