### ISSUE TITLE
Image width restriction falsely triggers when metadata file pre-exists

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#446]
Very weird issue, I just encountered. If I leave a metadata txt file, but delete the image, and then try to reupload it, the image width restriction error will trigger. Even though no image width restriction is set in the blueprint.

![screen shot 2015-04-29 at 20 05 51](https://cloud.githubusercontent.com/assets/3788865/7397865/792436a6-eeab-11e4-93a7-c8c6aeef9b5e.png)

The folder before uploading the image named `CIMG3459.jpg`:
![screen shot 2015-04-29 at 20 05 45](https://cloud.githubusercontent.com/assets/3788865/7397868/7a594480-eeab-11e4-9d3f-b50d4cac9bb8.png)

The blueprint:
```
<?php if(!defined('KIRBY')) exit ?>

title: Home
pages: false
files:
  fields:
    dimension:
      label: Dimension
      type: select
      required: true
      default: asp
      options:
        aut: Auto
        asp: Aspect
        ful: Full
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
    size:  large
```
