### ISSUE TITLE
Structure in site.php blueprint not displayed

### ISSUE THREAD

**Issue by tjeerdytsma** [getkirby/panel#468]
When adding a structure in the site.php blueprint it does not show on the 'Site options'-page of the panel. Also all fields that are declared after it do not show up.

**Comment by AugustMiller** [comment]
Can you post the entire contents of your `site.php` blueprint?

This sounds like a problem with the syntax, more than anything… I've used structure fields in the Site Options page for a while now without trouble.

**Comment by tjeerdytsma** [comment]
The problem occurs in the latest development version (ca44895). In panel version 2.0.1 (c170db6) it is working fine. My blueprint code is:
```
<?php if(!defined('KIRBY')) exit ?>

title: Site
pages: default
fields:    
  title:
    label: Title
    type:  text
  
  opties:
    label: Extra opties
    type: structure
    entry: >
      {{optie}}
    fields:
      optie:
        label: Optie
        type: text
  
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
  author:
    label: Author
    type:  text
```
