### ISSUE TITLE
"type: radio" doesn't work anymore

### ISSUE THREAD

**Issue by xu-chris** [getkirby/panel#51]
type: radio doesn't work. Look to these screenshots :-)

![bildschirmfoto 2014-05-06 um 16 58 25](https://cloud.githubusercontent.com/assets/980778/2891167/0cd523ce-d530-11e3-9499-5a124090d4e5.png)
![bildschirmfoto 2014-05-06 um 16 59 05](https://cloud.githubusercontent.com/assets/980778/2891168/0cd688f4-d530-11e3-95c2-18bea04e694c.png)

Code: 

```
type:
    label: Typ
    type: radio
    options:
        Theaterstück:  Theaterstück
        Kindertheater: Kindertheater
        Lesung: Lesung
        Gastspiel: Gastspiel
        Film: Film
        Musical: Musical
        Weihnachtsmärchen: Weihnachtsmärchen
```
