### ISSUE TITLE
custom translations

### ISSUE THREAD

**Issue by t128** [getkirby/panel#512]
Hi,

i tried to translate the field names in panel. But it seams like the */site/language/$code.php* file is not loaded by panel. Is there an other way to do this?

thanks

**Comment by malvese** [comment]
It is not in the Docs yet, but to translate fields names you can do something like
```yaml
fields:
  title:
    label: 
      en: Title
      fr: Titre
    type: text
  text:
    label:
      en: Text
      fr: Texte
```
Also make sure your multilingual setup works.
