### ISSUE TITLE
tags lowercase: true not functioning

### ISSUE THREAD

**Issue by SQbiz** [getkirby/panel#513]
the following field configuration is no longer forcing lowercase input:

```
  categories:
    label: Categories
    type: tags
    lowercase: true    
```

as an additional suggestion - it would be great if the `->filterBy(...)` method allowed for case-insensitive filtering.

**Comment by distantnative** [comment]
Just checked and the codes looks for `lower` instead of `lowercase`:

```
  categories:
    label: Categories
    type: tags
    lower: true 
```

I know that `lowercase` is in the docs, so I am wondering whether to change the docs or to change the code.
