### ISSUE TITLE
"type: tags" doesn't offer suggestions

### ISSUE THREAD

**Issue by xu-chris** [getkirby/panel#52]
I wanted to write "absurdes theater" but I don't get the suggestion for it:

![bildschirmfoto 2014-05-06 um 17 15 29](https://cloud.githubusercontent.com/assets/980778/2891301/4de24602-d531-11e3-838f-95330adb7110.png)

This is my code:

```
genre:
    label: Genre
    type: tags
    index: siblings
    lower: true
    data:
        - komödie
        - absurdes theater
```
