### ISSUE TITLE
Error when editing SFC entries (v2.2 beta)

### ISSUE THREAD

**Issue by sashtown** [getkirby/panel#582]
I ran into problems while editing existing structured field content entries in the latest beta version. The error is referencing to `[...]/app/fields/structure/forms/update.php` on line 5. After adding a new SFC entry to the same page everything works fine (on that page).

**Comment by distantnative** [comment]
I got a `Notice: Array to string conversion in …/panel/app/fields/structure/structure.php on line 111`

**Comment by bastianallgeier** [comment]
Could you post the blueprint code for that structure?

**Comment by distantnative** [comment]
No, I get the same error without using a multiselect field as well. Blueprint:

```
  tax:
    label: Tax rates
    type: structure
    entry: >
      {{rate}}: {{countries}}
    fields:
      rate:
        label: Tax rate
        type: text
      countries:
        label: Countries
        type: text
```

**Comment by distantnative** [comment]
Ah and sorry again, should have looked in the content file first. Still stuff left from the multiselect field that interfered:

```
qdyhEdvYSoLuxQO5z7b7rUwnC6INEcSN:
  rate: '3%'
  countries: de, en
  id: qdyhEdvYSoLuxQO5z7b7rUwnC6INEcSN
kNjhHSe6ttKkFDCpLtXMfeXoA7HV2Q8p:
  rate: "5%"
  countries[]:
    - de
    - en
  id: kNjhHSe6ttKkFDCpLtXMfeXoA7HV2Q8p
  countries: de
```

But I think that doesn't explain @sashtown's problem.

**Comment by sashtown** [comment]
The error occurs with multiple variations of structure setup, e.g.:

```
  cols:
    label: Columns
    type: structure
    fields:
      colheading:
        label: Column heading
        type: text
      colcontent:
        label: Column content
        type: textarea
```
Full error message:

```
Fatal error: Call to a member function toArray() on null in [...]/panel/app/fields/structure/forms/update.php on line 5
```
