### ISSUE TITLE
Select with Dynamic options inside Structure (v2.2 beta)

### ISSUE THREAD

**Issue by dionysiusmarquis** [getkirby/panel#598]
A ``Select field`` with ``Dynamic options`` inside a ``Structure field`` doesn't work with the current develop branch.

Example (``project`` field works fine ``project`` inside ``projects`` field doesn't):

```
fields:
  project:
    label: Project
    type: select
    options: query
    query: 
      page: projects
      fetch: children
      value: '{{uri}}'
      text: '{{title}}'
  projects:
    label: Projects
    type: structure
    entry: >
      {{project}}
    fields:
      project:
        label: Project
        type: select
        options: query
        query: 
          page: projects
          fetch: children
          value: '{{uri}}'
          text: '{{title}}'
```
