### ISSUE TITLE
Support non-associative array for `select` field option

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/panel#604]
Given the following blueprint:

```yaml
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
    size:  large
  bla:
    label: Category
    type: select
    options:
      Category A
      Category B
      Category C
```

Currently, the Panel will write the index number of the option to the content file (so if you select `Category B`, the value will be `2`). Shouldn't it be the displayed string in this case?

This issue has come up in the forum. I think it makes sense to support this syntax for use-cases without multi-language support and without any special conditional template magic (like if you simply want to display the value).
