### ISSUE TITLE
Fatal error when a structure file is edited

### ISSUE THREAD

**Issue by judbd** [getkirby/panel#607]
[2.2 beta] I have a bug when I try to edit a structured field : the modal shows up for a second the I have a blank page with this error :

`Fatal error: Call to a member function toArray() on a non-object in /panel/app/fields/structure/forms/update.php on line 5`

**Comment by lukasbestle** [comment]
Could you please post your blueprint?

**Comment by judbd** [comment]
Sure (the "recommandations" filed is the problematic one. I rolled back in 2.1 and I've no problem with the same blueprint/datas)

Sample datas below.

**template about.yml**
```
title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
    width: 1/2
  shortbiotitle:
    label: Short Title (displayed in footer)
    type:  text
    width: 1/2
  ShortBioText:
    label: Bio intro text
    type:  textarea
  Text:
    label: Project description (displayed on project page)
    type:  textarea
  SocialText:
    label: Sidebar text
    type:  textarea
  Name:
    label: Full name
    type:  text
    width: 1/4
  Phone:
    label: Phone number
    type:  text
    width: 1/4
  Address:
    label: Address
    type:  text
    width: 1/4
  job:
    label: Job
    type:  text
    width: 1/4
  twitter:
    label: Twitter
    type:  text
    width: 1/4
  flickr:
    label: Flickr
    type:  text
    width: 1/4
  github:
    label: Flickr
    type:  text
    width: 1/4
  blog:
    label: Blog
    type:  URL
    width: 1/4
  youtube:
    label: Youtube
    type:  URL
    width: 1/4
  email:
    label: Email
    type: email
  cvtitle:
    label: CV title
    type:  text
    width: 1/2
  CV:
    label: CV
    type:  textarea
  Recommandations:
    label: Recommandations
    type: structure
    fields:
      name:
        label: Name
        type: text
      recotext:
        label: Recommandation
        type: textarea
      job:
        label: Job
        type: text
      link:
        label: Link
        type: url
  SocialMedia:
    label: Réseaux sociaux
    type: structure
    fields:
      platform:
        label: username
        type: text
      username:
        label: username
        type: text
      link:
        label: link to profile
        type: text
      icon:
        label: font awesome icon name
        type: text
  brands:
    label: Additionnal brands (in addition to those set in each project)
    type:  textarea
```

**Datas**
```
- name: Marie-Anaïs
  recotext: Il est tellement doué que si ça n'était pas déjà mon mari je l'épouserai.
  job: Contrôleuse qualité chez vente-privee.com
  link:
  
- name: Christophe
  recotext: J’ai réalisé plusieurs sites avec Julien, que ce soit dans un cadre professionnel ou sur des projets bénévoles. Son savoir-faire, sa rigueur et l’acharnement qu’il met à défendre la qualité dans son métier en font un collaborateur éclairé et un allié précieux.
  job: Dev Front et web designer
  link: http://

- name: Vincent
  recotext: Julien est un mec bien qui fait tout son possible pour ne pas le montrer. (Spoiler:&nbsp;ça marche.)
  C’est aussi une vraie force créative et expert en communication avéré. Il apporte sans aucun doute une forte valeur ajoutée là où il intervient de par ses compétences et son engagement.
  job: Dev Front et web designer
  link: http://	
  
- name: Goulven
  recotext: Derrière le personnage, il y a un vrai engagement de Julien pour la communauté des professionnels du graphisme français.
  job: Graphiste et formateur
  link: http://
```
