### ISSUE TITLE
Custom field CSS not loaded (2.2 beta)

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#619]
Since the js and css restructuring in the panel, the multiselect css doesn't seem to load anymore.

Blueprint:
```
  switchit:
    label: Switch
    type: switch
    text_on: See, it works!
    text_off: Could it work?
  rel_articles:
   label: Articulos relacionados
   type: multiselect
   search: true
   options: pages
```

Both are custom fields. Switch Field does reference CSS like this:
```php
  static public $assets = array(
     'css' => array(
       'style.css'
     )
   );
```

Multiselect Field liek this:
```php
  static public $assets = array(
    'css' => array(
      'multiselect.css'
     ),
    'js' => array(
      'multiselect.js'
    )
  );
```

But only the switch field css ends up in the plugin.css. Any idea why?
