### ISSUE TITLE
Changes.php - call to value() on NULL (2.2)

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#629]
No idea how i walked into this issue, but I'm getting the following error on trying to edit my `home` page:

```
Fatal error: Call to a member function value() on null in …/panel/app/src/panel/models/page/changes.php on line 70
```

Content file:
```
Title: Home

----

Text:

Yay! If you are seeing this, the installation of Kirby worked. :)

## Get started

- Go to the (link: panel text: panel) to give Kirby's admin interface a try
- Check out the (link: http://getkirby.com/docs text: docs) and start building your own site
- Follow (twitter: @getkirby) on Twitter for updates
- Visit the (link: http://forum.getkirby.com text: forum) to connect with other Kirby users
- (link: http://getkirby.com/support text: Get in contact) if you need support.

**Have fun with Kirby!**
```

Blueprint:
```
<?php if(!defined('KIRBY')) exit ?>

title: Home
pages: false
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
    size:  large
```
