### ISSUE TITLE
Datetime field still requires something

### ISSUE THREAD

**Issue by creichel** [getkirby/panel#654]
I'm tried to use the awesome new datetime field with two different fields in one structure field: `startdate` and `enddate` (basically for a `events` structure field). 
While the startdate is required, the enddate is optional. But when I try to click "Add", I'm getting this: 
<img width="1049" alt="bildschirmfoto 2015-11-14 um 22 39 48" src="https://cloud.githubusercontent.com/assets/980778/11165960/d8204d2c-8b20-11e5-8e24-5950b3fc7752.png">

Seems like the datetime-field `enddate` still needs some kind of input. I think this is a little bug.

The part of my blueprint to test and discuss:
```
  events:
    label: Events
    type: structure
    modalsize: large
    style: table
    fields:

      startdate:
        label: Startdatum
        type: datetime
        width: 1/2
        format: DD.MM.YYYY
        required: true
      enddate:
        label: Enddatum
        type: datetime
        format: DD.MM.YYYY
        width: 1/2
        help: Nur bei Gastspielen oder Events.
        required: false
```

BTW: you're awesome! I fell in love with Kirby v 2.2!
