### ISSUE TITLE
error with structure fields in 2.2

### ISSUE THREAD

**Issue by jensfranke** [getkirby/panel#657]
With the latest version of the dev-branches (kirby, panel, toolkit) I get the following error if I try to add content to a structure field:

````
Fatal error: Call to a member function fields() on null in … /panel/structure.php on line 74
````

My field definition in the blueprint:

```
fields:
  test:
    label: Test field
    type: structure
    entry: >
      {{demo}}
    fields:
      demo:
        label: Demo-Label
        type: text

```

Is my definition wrong?

**Comment by distantnative** [comment]
Just tested it and it's working for me:
```
title: Home
pages: false
files: false
fields:
  title:
    label: Title
    type:  text
  test:
    label: Test field
    type: structure
    entry: >
      {{demo}}
    fields:
      demo:
        label: Demo-Label
        type: text
```

Are you on the most recent version of the 2.2 / of the develop branch? Structure fields have undergone quite some bugfixing. And are all your indentations right?
