### ISSUE TITLE
Changing field type of title field

### ISSUE THREAD

**Issue by creichel** [getkirby/panel#658]
In one of my blueprints I want to simply let the user select a name from a list - in this case a month. So I tried to change the type of the title field in my blueprint:

```
  title:
    label: Monat
    type: select
    options:
      Januar: Januar
      Februar: Februar
      März: März
      April: April
      Mai: Mai
      Juni: Juni
      Juli: Juli
      August: August
      September: September
      Oktober: Oktober
      November: November
      Dezember: Dezember
    icon: calendar-o
    width: 1/2
```

I expected to see a select field now in the panel, but all I get is this:
<img width="508" alt="bildschirmfoto 2015-11-15 um 18 02 52" src="https://cloud.githubusercontent.com/assets/980778/11169833/208b1e5a-8bc3-11e5-9906-9c40f981cc29.png">
Test System: Kirby v2.2

Is this a "normal" behavior?
