### ISSUE TITLE
Set the time-interval for datetime-fields

### ISSUE THREAD

**Issue by schmidtflo** [getkirby/panel#662]
In Kirby 2.2 the datetime-blueprint-fields were added. But it's not possible to set the interval for the time like on the time-blueprint-field. At the moment only 1-hour-steps are possible.

**Comment by bastianallgeier** [comment]
You can modify the time format like this: 

```
datetime: 
  label: Date
  type: datetime
  time: 
    interval: 15 
```

Available fields for time: format (12 or 24) and interval
Available fields for date: format
