### ISSUE TITLE
Feature request: Structure field "table style" controls

### ISSUE THREAD

**Issue by NECKRHINOS** [getkirby/panel#666]
I really like the possibility for displaying structured field contents in the panel as a table, i. e. using "style: table" in its corresponding blueprint.

However, I have some feature requests for this style type:
- Optional alphabetical sorting
- More controls for entries: Don't show all entries as columns but a selection, something like: "entries: 2" for example

Something else that' be great having would be:
- Search for structured field contents – Either via Kirby search or as a seperate search field when having a structure field in the panel

( P.S.: Issue #666, hey! :+1:  )

**Comment by FabianSperrle** [comment]
I just did exactly that today and thought I'd share my stuff, maybe it can help to determine a working/intuitive syntax for the blueprints: 

```yml
participants:
    label: Participants
    type: structure
    style: table
    show:
      - column1
      - column2
      - column3
    colors:
      column1:
        value1: d9edf7
        value2: d9edf7
      column3:
        v1: dff0d8
    fields:
      column1:
        label: Column 2
        width: 1/2
      column2:
        label: Column 2
        width: 1/2
      column3:
        label: Column 3
```

The color part is not really related to this issue, but still a nice effect I think :-)
I had to make the following code changes:

```php
// structure.php
public function show() {

  $output = array();

  foreach ($this->fields() as $field) {
    if (in_array($field['name'], $this->show)) {
      $output[] = $field;
    }
  }

  return $output;

}
```

And in `table.php` you just have to replace

```php
<?php foreach ($field->fields()): ?>
  ...
<?php endforeach; ?>
```

with 

```php
<?php foreach ($field->show()): ?>
  ...
<?php endforeach; ?>
```

------------

The color part is very hacky:

```
// table.php 

<tbody>
  <?php foreach($field->entries() as $entry): ?>
   <?php $color = $field->color($entry); ?>
    <tr id="structure-entry-<?php echo $entry->id() ?>">
      <?php foreach($field->show() as $f): ?>
        <td <?php if ($color != null): ?> style="background-color: #<?= $color ?><?php endif; ?>">


// structure.php

public function color($entry) {

  foreach ($this->colors() as $field => $conditions) {
    foreach ($conditions as $condition => $color) {
      if ($entry->{$field} == $condition) {
        return $color;
      }
    }
  }

  return null;

}
```

**Comment by bastianallgeier** [comment]
I think this should all go into the field definitions. I will think about it some more for the next release.

**Comment by lukasbestle** [comment]
The columns to display are now configurable like this on the develop branch:

```yaml
fields:
  addresses:
    label: Addresses
    type: structure
    style: table
    entry:
      - street
      - city
    fields:
      street:
        label: Street
        type: text
      zip:
        label: ZIP
        type: text
      city:
        label: City
        type: text
```

The other requests (search, alphabetical sorting, colors) are not implemented. Please reopen as new GitHub issues if you still want those features. Thanks!
