### ISSUE TITLE
$page->update() removes content

### ISSUE THREAD

**Issue by helllicht** [getkirby/panel#667]
That's an big issue, $page->update() removes content from txt file.

$page->update(array(
  'description' => 'Lorem Ipsum'
));

Clears all fields expect of 'description' and 'title'.

**Comment by bastianallgeier** [comment]
The update method in the panel keeps only those fields in the blueprint.

**Comment by bastianallgeier** [comment]
I just double-checked just to be 100% sure and this is something that was handled in the same way in previous versions.

**Comment by helllicht** [comment]
```php
// triggerd via hook panel.page.update
$page->update(array(
   'autoid' => '1'
));
```

```yaml
# blueprint
title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  year:
    label: Year
    type:  text
  text:
    label: Text
    type:  textarea
  tags:
    label: Tags
    type:  tags
  autoid:
    label: id
    type:  input
```

After clicking "Save" everything expect 'autoid' and 'title' is empty.
