### ISSUE TITLE
User blueprint select query not working

### ISSUE THREAD

**Issue by FabianSperrle** [getkirby/panel#672]
I just tried the new user blueprints and they don't seem to work with select fields with a specified query:

```php
# site/blueprints/users/role.yml

fields:
  group:
    label: Group
    type: select
    options: query
    query: 
      page: groups
      fetch: visibleChildren
      value: '{{title}}'
      text: '{{title}}'
```

The field is displayed, but the list of options is empty. The exact same snippet is working everywhere else in the panel.

**Comment by FabianSperrle** [comment]
Quick note: The blueprint works if I specify a fixed list of options.

**Comment by samnabi** [comment]
Even without `query`, options don't show up:

```
fields:
  country:
    label: Featured page
    type: select
    options: pages
```
