### ISSUE TITLE
Field Validation Not Working

### ISSUE THREAD

**Issue by CalebGrove** [getkirby/panel#679]
So, I have this in my blueprint:

````
audiofile:
    label: Audio File URL
    type: url
    required: true
    help: A public link directly to the MP3 file.
````

When I enter a non-URL string into the field (`hello world`), there is no error message. I'm using Kirby 2.2.
