### ISSUE TITLE
Unchecking checkboxes not working in 2.2.2

### ISSUE THREAD

**Issue by texnixe** [getkirby/panel#684]
If checkboxes are unchecked, the file can be saved but the content is not saved to file and the field is checked again. The content can be overwritten if another checkbox is checked, but not possible to save no value at all (tested with testkit).

https://forum.getkirby.com/t/blueprints-checkboxes-bug-wont-save-an-empty-list/2652/4
https://forum.getkirby.com/t/saving-unchecked-checkboxes-field/2635/12

**Comment by jevets** [comment]
On 2.2.1, checkboxes on regular pages do work. 

But checkboxes on user blueprints suffer the same issue as 2.2.2, (not saving an empty list).

```yaml
// site/blueprints/users/admin.yml
fields:
  checks:
    label: Checks Test
    type: checkboxes
    options:
      one: One
      two: Two
      three: Three
```

```
Kirby info
Toolkit version: 2.2.1
Kirby version: 2.2.1
Panel version: 2.2.1
```
