### ISSUE TITLE
Tags: Autocompletion of tags doesn't work at files

### ISSUE THREAD

**Issue by creichel** [getkirby/panel#699]
Here's the blueprint:

```
files:
  sortable: true
  fields:
    photograph:
      label:
        de: Fotograf
        en: Photograph
      type: tags
      index: siblings
      icon: copyright
```

I tried everything. Even setting the index to `all` doesn't work.
