### ISSUE TITLE
idea: classes for fields

### ISSUE THREAD

**Issue by SQbiz** [getkirby/panel#723]
It would be nice to have classes applied to the fields in the panel - either based on the title or an additional `class` option defined in the blueprint.

An example:

field in blueprint:
```
  client_logos:
    class: structure-images
    label: Client Logos
    type: structure
    entry: <img src="/home/{{logo_image}}">
    fields:
      logo_image:
        label: Image
        type: selector
        mode: single
        size: 4
        options:
          - image
````

CSS:
````
.structure-images .structure-entry {
   width: 25%;
   float: left;
}

.structure-images .structure-entry-content {
    height: 10rem;
    overflow: hidden;
    display: flex;
    align-items: center;
}
````

Result:
![panel](http://cl.ly/2V0e2O1T3v1s/download/Image%202016-01-04%20at%206.59.43%20PM.png)
