### ISSUE TITLE
Site settings not saving with required email field and translate:false

### ISSUE THREAD

**Issue by venller** [getkirby/panel#796]
Good afternoon!!
I have a problem with the blueprint of "site" when I work with a multilanguage panel.
This is the structure:
```
email:
    label: Contact Form Email
    type: email
    translate: false
    required: true
```
I have to change the type into "text" in order to save the content, otherwise, it fails...
Many thanks, the toolkit is awesome.
#
