### ISSUE TITLE
structure field hide table columns in list view

### ISSUE THREAD

**Issue by klloe** [getkirby/panel#809]
Instead of going with evil :imp: #666 this would be a simpler approach. Just add the ability to **hide** long columns like a description (_textarea_) in the list view. Not that complicated, but hey this is Kirby! 

```
  items:
    label: Items
    type: structure
    style: table
    hide:
      - short
      - description
    fields:
      item: ...
      short: ...
      description: ...
      price: ...
      ingredients: ...
```

![2016-03-12-122245_1280x800_scrot](https://cloud.githubusercontent.com/assets/1057526/13722638/0dcb592e-e84d-11e5-9bf3-1ddf5a8a4bb4.png)
