### ISSUE TITLE
Odd behavior when title is inside a structure field

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#814]
```yaml
fields:
  nav:
    label: Meny
    type: structure
    style: table
    fields:
      page:
        label: Sida
        type: fragment
        uri: parents/parents
      title:
        label: Rubrik
        type: text
```

![image](https://cloud.githubusercontent.com/assets/927011/13775050/b5f8875a-eaa2-11e5-8800-03bd497be67f.png)

If title is not allowed inside a structure field, then throw an error.

However because title is not a field, but a field of a field, then it should be allowed. It's `fields/fields/title`.

**If it's allowed:**

- Don't force required of this field (*).
- Don't show the slug.
- Deattach whatever is attached to a main title field, so there is no weird behavior when using it, saving it etc.

**Comment by distantnative** [comment]
All fields named `title` will be converted to the TitleField type automatically.

**Comment by jenstornell** [comment]
A few solutions comes to mind...

## Be aware of level

If a field is called `title` and it's a child of `fields`, then convert it to a title field. (If it's a grandchild, don't)

## Introduce a title field

I think it's a little weird that a text field in some cases just are converted to a title field. Maybe separate them?

```yaml
fields:
  title:
    label: Title
    type: title
```
