### ISSUE TITLE
No alert for replaced field when switching template (2.3 beta 2)

### ISSUE THREAD

**Issue by malvese** [getkirby/panel#847]
I have a page using a `markdown` blueprint:
```
…
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  markdown
```
And want to switch it to the `projects` blueprint (plural, from the starterkit):

```
…
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
```
The Panel should tell me that the "text" field will be replaced, as it uses a different field type. But there's no alert, if I click "Change" the "Text" field is lost.
If I try to switch to `project` (singular), I'm correctly told there are added fields (Year, Tags) and a replaced field (Text).
It seems the modal tells about the replaced field only if there are other field changes.

![template-switch](https://cloud.githubusercontent.com/assets/193492/15027267/3e17dd26-1243-11e6-8798-435474d503ed.png)
