### ISSUE TITLE
Specifying `buttons` of textarea as empty doesn't work inside a structure

### ISSUE THREAD

**Issue by dkerzig** [getkirby/panel#854]
Hey guys,
I've tried to remove all buttons of a textarea with "buttons:" (just leaving it empty) which works perfectly in all my blueprints. But when I try this inside a structure (see last row of the snippet below) the "Bold" and "Italic" buttons are still showing up. 

```
  events:
    label: Events
    type: structure
    entry: >
      {{name}} am {{datetime}}<br />
      {{description}}
    fields:
      name:
        label: Event-Name
        type: text
      datetime:
        label: Datum und Zeit
        type:  datetime
      description:
        label: Kurzbeschreibung
        type: textarea
        buttons:
```

<img width="452" alt="bildschirmfoto 2016-05-25 um 18 43 13" src="https://cloud.githubusercontent.com/assets/3930150/15548420/940ffa90-22a8-11e6-8be5-988e90fee224.png">

I've found out that I can prevent this by specifying an empty list (see below) but nonetheless I think this is a bug, isn't it?

```
        buttons:
          -
```

Dennis (Using Kirby 2.3)
