### ISSUE TITLE
blueprint mode: date not working with fieldtype datetime

### ISSUE THREAD

**Issue by stereonom** [getkirby/panel#865]
This is my Blog blueprint:
```
title: Blog
pages: 
	template: post
	num:
		mode: date
		field: published
		format: YmdHi
fields:
	title:
		label: Title
		type:  text
```

This is my Post blueprint:

```
title: Post
pages:
	mode: date
	field: published
files:
  sortable: false
fields:
  title:
    label: Title
    type:  text
  published:
    label: Published
    type:  datetime
``` 
The panel doesn't sort by the datetime I guess?
