### ISSUE TITLE
Don't show "Page settings" if there are none

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#877]
![image](https://cloud.githubusercontent.com/assets/927011/16307019/158b818e-3960-11e6-8f53-9d6fbb41f146.png)

No need to show the "Page settings" label if there are no page settings.

**This i my yaml:**

```yml
title: My title
files: false
preview: false
options:
  preview: false
  status: false
  template: false
  url: false
  delete: false
fields:
```
