### ISSUE TITLE
Structure field are stored wrong by the panel

### ISSUE THREAD

**Issue by atimoda** [getkirby/panel#880]
When you insert data on some Structure Field through the panel, the panel saves the user file with this kind of indentation (example):

```
testfield:
  - 
    city: New York
    country: US
  - 
    city: Paris
    country: France
  - 
    city: Sao Paulo
    country: Brazil
```

But the two methods "yaml()" and "toStructure()" cant handle well this kind of indentation. For example, if you try to run a loop to echo all the "cities", like this:

```
foreach($page->testfield()->toStructure() as $item):
  echo $item->local() . '<br>';
endforeach;
```

You end up with the result:

```
Sao Paulo
```

But it should instead output the result like this:

```
New York
Paris
Sao Paulo
```

So the correct indentation, which yaml() and toStructure() recognizes and work well, is this way:

```
testfield:
- city: New York
  country: US
- city: Paris
  country: France
- city: Sao Paulo
  country: Brazil
```

So the panel should write the structure fields using the "correct" indentation.... another solution would be the "yaml" and "toStructure" being smarter in the way they recognize indentation.
