### ISSUE TITLE
Character counter needs z-index to be visible at file view

### ISSUE THREAD

**Issue by jakobploens** [getkirby/panel#900]

**Comment by jakobploens** [comment]
In v2.3.2, the counter isn't applied at all, for both `max` and `maxLength`.

**Comment by lukasbestle** [comment]
Which browser on which OS are you using? Could you please post the full blueprint?

**Comment by jakobploens** [comment]
FirefoxDeveloperEdition on OS X El Capitan. Just tested it in Safari, it works there without problems. Chrome also needs the custom stylesheet. All browsers are the latest available version.

My blueprint:

```
# site/blueprints/home.yml

title: Startseite
icon:  home
pages: false
files:
    sortable: true
    fields:
        link:
            label: Link
            type:  url
        alt: alt
        text:
            label: Text
            type:  textarea

# site/blueprints/fields/alt.yml

label: Alternativ-Text
type:  text
validate:
    maxLength: 50

```

Direct implementation without the field definition doesn't change anything. The markup seems to be correct, so I guess it's really just a CSS problem…
