### ISSUE TITLE
Panel field checkboxes long label issue

### ISSUE THREAD

**Issue by monobasic** [getkirby/panel#905]
When texts for panel checkboxes labels getting longer, column layout is not calculated correct any more and the fields overlap the current viewport width.

1-col:
https://www.dropbox.com/s/1nnqu9iiu58krq6/Screenshot%202016-08-23%2010.26.31.png?dl=0

2-col mobile:
https://www.dropbox.com/s/qe3gb0n2qflmq2v/Screenshot%202016-08-23%2010.28.57.png?dl=0

**Comment by monobasic** [comment]
Link to issue @ kirby forum: https://forum.getkirby.com/t/panel-field-checkboxes-long-label-issue/5043

**Comment by lukasbestle** [comment]
Could you please post your blueprint? I have tested this in several browser and long text wraps to the next line inside the checkbox field.

**Comment by texnixe** [comment]
I tested this as well and the text did not wrap ... (Safari and Chrome)

**Comment by lukasbestle** [comment]
Can I have the blueprint you were using?

**Comment by texnixe** [comment]
Sure

```
title: Home
pages: false
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  checky:
    label: Checkboxes
    type: checkboxes
    options:
      a:a jfdjf dakjfdaks jakjd fasj kfjdsfk jasdkj jakj fakjd kajdf kajf kaj kfajk fjadsö kfjkasj f
      b: aj dkajsf kajsdfkj asdkfj asjdfkasjf  jdkjfkajd ajdfkjadfk jadskfj akjdf kasjf kadjfk kjdf
```
