### ISSUE TITLE
Idea: Field options: `files` query option

### ISSUE THREAD

**Issue by p-h-i-l** [getkirby/panel#923]
Allow query to fetch list of files not only from a page but also from a specified asset folder.

Edit: Was also requested before....
https://forum.getkirby.com/t/select-image-from-assets-in-panel/3551

**Comment by lukasbestle** [comment]
As you wrote, fetching files from another page already works. Asset directories outside of the content directory won't be supported by the Panel though, this makes it all very complex and might introduce security issues.

**Comment by p-h-i-l** [comment]
Hmmm, i thought it would be cool to access an assets folder with icons for e.g. an icon field. But i guess a custom field is the way to go then? 

Another option would be to have a parent page which stores the icons. Like e.g. an invisible page for managing categories. For that scenario i am missing 'parent' and 'grandParents [visible] [invisible]' fetch options ... :(

**Comment by lukasbestle** [comment]
You could use a page in the root of the site directory and use the `query` option with `page`:

```
fields:
    icon:
      label: Icon
      type: select
      options: query
       query:
          page: assets
          fetch: files
```
