### ISSUE TITLE
Checkboxes field loads JSON options for every checkbox again

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#998]
While I tried to debug https://github.com/distantnative/field-multiselect/issues/21 I found that his is a general problem with the checkboxes field and also the radio field I believe:

When querying the options form a JSON file like
```
currency:
    label: Account Currencies
    type: checkboxes
    options: https://99bookmakers.com/api/currency.json
```

Because of https://github.com/getkirby/panel/blob/master/app/fields/checkboxes/checkboxes.php#L14 with https://github.com/getkirby/panel/blob/master/app/fields/checkboxes/checkboxes.php#L31 and https://github.com/getkirby/panel/blob/master/app/fields/inputlist/inputlist.php#L14, the panel loads the JSON file for every checkbox again, instead of caching it. 

Which obviously slows down the panel extremely.
